/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AuthenticatedIndexRouteImport } from './routes/_authenticated/index'
import { Route as AuthenticatedVetSummaryRouteImport } from './routes/_authenticated/vet-summary'
import { Route as AuthenticatedVaccinationsRouteImport } from './routes/_authenticated/vaccinations'
import { Route as AuthenticatedTreatmentsRouteImport } from './routes/_authenticated/treatments'
import { Route as AuthenticatedScannerRouteImport } from './routes/_authenticated/scanner'
import { Route as AuthenticatedReportsRouteImport } from './routes/_authenticated/reports'
import { Route as AuthenticatedRecordsRouteImport } from './routes/_authenticated/records'
import { Route as AuthenticatedOfflineAiRouteImport } from './routes/_authenticated/offline-ai'
import { Route as AuthenticatedMoreRouteImport } from './routes/_authenticated/more'
import { Route as AuthenticatedHistoryRouteImport } from './routes/_authenticated/history'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedAnimalsRouteImport } from './routes/_authenticated/animals'
import { Route as AuthenticatedAlertsRouteImport } from './routes/_authenticated/alerts'
import { Route as AuthenticatedAnimalsAnimalIdRouteImport } from './routes/_authenticated/animals.$animalId'

const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedIndexRoute = AuthenticatedIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedVetSummaryRoute = AuthenticatedVetSummaryRouteImport.update({
  id: '/vet-summary',
  path: '/vet-summary',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedVaccinationsRoute =
  AuthenticatedVaccinationsRouteImport.update({
    id: '/vaccinations',
    path: '/vaccinations',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedTreatmentsRoute = AuthenticatedTreatmentsRouteImport.update({
  id: '/treatments',
  path: '/treatments',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedScannerRoute = AuthenticatedScannerRouteImport.update({
  id: '/scanner',
  path: '/scanner',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedReportsRoute = AuthenticatedReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedRecordsRoute = AuthenticatedRecordsRouteImport.update({
  id: '/records',
  path: '/records',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedOfflineAiRoute = AuthenticatedOfflineAiRouteImport.update({
  id: '/offline-ai',
  path: '/offline-ai',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedMoreRoute = AuthenticatedMoreRouteImport.update({
  id: '/more',
  path: '/more',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedHistoryRoute = AuthenticatedHistoryRouteImport.update({
  id: '/history',
  path: '/history',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAnimalsRoute = AuthenticatedAnimalsRouteImport.update({
  id: '/animals',
  path: '/animals',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAlertsRoute = AuthenticatedAlertsRouteImport.update({
  id: '/alerts',
  path: '/alerts',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAnimalsAnimalIdRoute =
  AuthenticatedAnimalsAnimalIdRouteImport.update({
    id: '/$animalId',
    path: '/$animalId',
    getParentRoute: () => AuthenticatedAnimalsRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof AuthenticatedIndexRoute
  '/auth': typeof AuthRoute
  '/alerts': typeof AuthenticatedAlertsRoute
  '/animals': typeof AuthenticatedAnimalsRouteWithChildren
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/history': typeof AuthenticatedHistoryRoute
  '/more': typeof AuthenticatedMoreRoute
  '/offline-ai': typeof AuthenticatedOfflineAiRoute
  '/records': typeof AuthenticatedRecordsRoute
  '/reports': typeof AuthenticatedReportsRoute
  '/scanner': typeof AuthenticatedScannerRoute
  '/treatments': typeof AuthenticatedTreatmentsRoute
  '/vaccinations': typeof AuthenticatedVaccinationsRoute
  '/vet-summary': typeof AuthenticatedVetSummaryRoute
  '/animals/$animalId': typeof AuthenticatedAnimalsAnimalIdRoute
}
export interface FileRoutesByTo {
  '/auth': typeof AuthRoute
  '/alerts': typeof AuthenticatedAlertsRoute
  '/animals': typeof AuthenticatedAnimalsRouteWithChildren
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/history': typeof AuthenticatedHistoryRoute
  '/more': typeof AuthenticatedMoreRoute
  '/offline-ai': typeof AuthenticatedOfflineAiRoute
  '/records': typeof AuthenticatedRecordsRoute
  '/reports': typeof AuthenticatedReportsRoute
  '/scanner': typeof AuthenticatedScannerRoute
  '/treatments': typeof AuthenticatedTreatmentsRoute
  '/vaccinations': typeof AuthenticatedVaccinationsRoute
  '/vet-summary': typeof AuthenticatedVetSummaryRoute
  '/': typeof AuthenticatedIndexRoute
  '/animals/$animalId': typeof AuthenticatedAnimalsAnimalIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/_authenticated/alerts': typeof AuthenticatedAlertsRoute
  '/_authenticated/animals': typeof AuthenticatedAnimalsRouteWithChildren
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/history': typeof AuthenticatedHistoryRoute
  '/_authenticated/more': typeof AuthenticatedMoreRoute
  '/_authenticated/offline-ai': typeof AuthenticatedOfflineAiRoute
  '/_authenticated/records': typeof AuthenticatedRecordsRoute
  '/_authenticated/reports': typeof AuthenticatedReportsRoute
  '/_authenticated/scanner': typeof AuthenticatedScannerRoute
  '/_authenticated/treatments': typeof AuthenticatedTreatmentsRoute
  '/_authenticated/vaccinations': typeof AuthenticatedVaccinationsRoute
  '/_authenticated/vet-summary': typeof AuthenticatedVetSummaryRoute
  '/_authenticated/': typeof AuthenticatedIndexRoute
  '/_authenticated/animals/$animalId': typeof AuthenticatedAnimalsAnimalIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/alerts'
    | '/animals'
    | '/dashboard'
    | '/history'
    | '/more'
    | '/offline-ai'
    | '/records'
    | '/reports'
    | '/scanner'
    | '/treatments'
    | '/vaccinations'
    | '/vet-summary'
    | '/animals/$animalId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/auth'
    | '/alerts'
    | '/animals'
    | '/dashboard'
    | '/history'
    | '/more'
    | '/offline-ai'
    | '/records'
    | '/reports'
    | '/scanner'
    | '/treatments'
    | '/vaccinations'
    | '/vet-summary'
    | '/'
    | '/animals/$animalId'
  id:
    | '__root__'
    | '/_authenticated'
    | '/auth'
    | '/_authenticated/alerts'
    | '/_authenticated/animals'
    | '/_authenticated/dashboard'
    | '/_authenticated/history'
    | '/_authenticated/more'
    | '/_authenticated/offline-ai'
    | '/_authenticated/records'
    | '/_authenticated/reports'
    | '/_authenticated/scanner'
    | '/_authenticated/treatments'
    | '/_authenticated/vaccinations'
    | '/_authenticated/vet-summary'
    | '/_authenticated/'
    | '/_authenticated/animals/$animalId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/': {
      id: '/_authenticated/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/vet-summary': {
      id: '/_authenticated/vet-summary'
      path: '/vet-summary'
      fullPath: '/vet-summary'
      preLoaderRoute: typeof AuthenticatedVetSummaryRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/vaccinations': {
      id: '/_authenticated/vaccinations'
      path: '/vaccinations'
      fullPath: '/vaccinations'
      preLoaderRoute: typeof AuthenticatedVaccinationsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/treatments': {
      id: '/_authenticated/treatments'
      path: '/treatments'
      fullPath: '/treatments'
      preLoaderRoute: typeof AuthenticatedTreatmentsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/scanner': {
      id: '/_authenticated/scanner'
      path: '/scanner'
      fullPath: '/scanner'
      preLoaderRoute: typeof AuthenticatedScannerRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/reports': {
      id: '/_authenticated/reports'
      path: '/reports'
      fullPath: '/reports'
      preLoaderRoute: typeof AuthenticatedReportsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/records': {
      id: '/_authenticated/records'
      path: '/records'
      fullPath: '/records'
      preLoaderRoute: typeof AuthenticatedRecordsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/offline-ai': {
      id: '/_authenticated/offline-ai'
      path: '/offline-ai'
      fullPath: '/offline-ai'
      preLoaderRoute: typeof AuthenticatedOfflineAiRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/more': {
      id: '/_authenticated/more'
      path: '/more'
      fullPath: '/more'
      preLoaderRoute: typeof AuthenticatedMoreRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/history': {
      id: '/_authenticated/history'
      path: '/history'
      fullPath: '/history'
      preLoaderRoute: typeof AuthenticatedHistoryRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/animals': {
      id: '/_authenticated/animals'
      path: '/animals'
      fullPath: '/animals'
      preLoaderRoute: typeof AuthenticatedAnimalsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/alerts': {
      id: '/_authenticated/alerts'
      path: '/alerts'
      fullPath: '/alerts'
      preLoaderRoute: typeof AuthenticatedAlertsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/animals/$animalId': {
      id: '/_authenticated/animals/$animalId'
      path: '/$animalId'
      fullPath: '/animals/$animalId'
      preLoaderRoute: typeof AuthenticatedAnimalsAnimalIdRouteImport
      parentRoute: typeof AuthenticatedAnimalsRoute
    }
  }
}

interface AuthenticatedAnimalsRouteChildren {
  AuthenticatedAnimalsAnimalIdRoute: typeof AuthenticatedAnimalsAnimalIdRoute
}

const AuthenticatedAnimalsRouteChildren: AuthenticatedAnimalsRouteChildren = {
  AuthenticatedAnimalsAnimalIdRoute: AuthenticatedAnimalsAnimalIdRoute,
}

const AuthenticatedAnimalsRouteWithChildren =
  AuthenticatedAnimalsRoute._addFileChildren(AuthenticatedAnimalsRouteChildren)

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAlertsRoute: typeof AuthenticatedAlertsRoute
  AuthenticatedAnimalsRoute: typeof AuthenticatedAnimalsRouteWithChildren
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedHistoryRoute: typeof AuthenticatedHistoryRoute
  AuthenticatedMoreRoute: typeof AuthenticatedMoreRoute
  AuthenticatedOfflineAiRoute: typeof AuthenticatedOfflineAiRoute
  AuthenticatedRecordsRoute: typeof AuthenticatedRecordsRoute
  AuthenticatedReportsRoute: typeof AuthenticatedReportsRoute
  AuthenticatedScannerRoute: typeof AuthenticatedScannerRoute
  AuthenticatedTreatmentsRoute: typeof AuthenticatedTreatmentsRoute
  AuthenticatedVaccinationsRoute: typeof AuthenticatedVaccinationsRoute
  AuthenticatedVetSummaryRoute: typeof AuthenticatedVetSummaryRoute
  AuthenticatedIndexRoute: typeof AuthenticatedIndexRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAlertsRoute: AuthenticatedAlertsRoute,
  AuthenticatedAnimalsRoute: AuthenticatedAnimalsRouteWithChildren,
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedHistoryRoute: AuthenticatedHistoryRoute,
  AuthenticatedMoreRoute: AuthenticatedMoreRoute,
  AuthenticatedOfflineAiRoute: AuthenticatedOfflineAiRoute,
  AuthenticatedRecordsRoute: AuthenticatedRecordsRoute,
  AuthenticatedReportsRoute: AuthenticatedReportsRoute,
  AuthenticatedScannerRoute: AuthenticatedScannerRoute,
  AuthenticatedTreatmentsRoute: AuthenticatedTreatmentsRoute,
  AuthenticatedVaccinationsRoute: AuthenticatedVaccinationsRoute,
  AuthenticatedVetSummaryRoute: AuthenticatedVetSummaryRoute,
  AuthenticatedIndexRoute: AuthenticatedIndexRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
